language: go

go:
#  - 1.1 // ql fails to compile on go1.2+.
  - 1.2
  - 1.2.1
  - 1.3
  - 1.3.1

env:
  - GOARCH=amd64

install:
  - sudo apt-get install bzr
  # - go get github.com/cznic/ql/ql # ql command line util.
  # - go install github.com/cznic/ql/ql # ql command line util.
  - go get -t -d
  # - go get github.com/elsonwu/db/mongo
  # - go get github.com/elsonwu/db/mysql
  # - go get github.com/elsonwu/db/postgresql
  # - go get github.com/elsonwu/db/sqlite
  # - go get github.com/elsonwu/db/ql

services:
  - mongodb

before_script:
  - cat mysql/_dumps/setup.sql | mysql -uroot
  - cat mysql/_dumps/structs.sql | mysql -uupperio -pupperio upperio_tests
  - cat postgresql/_dumps/setup.sql | psql -U postgres
  - cat postgresql/_dumps/structs.sql | PGPASSWORD="upperio" psql -U upperio upperio_tests
  - mongo upperio_tests --eval 'db.addUser("upperio", "upperio")'
  # - cat ql/_dumps/structs.sql | $GOPATH/bin/ql -db ql/_dumps/test.db

script:
  - go version
  - go test -host 127.0.0.1
